site_name: gist-geckos documentation
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - toc.integrate
    - navigation.top
    - search.suggest
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle: 
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list 
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: 'index.md'
  - Overview: 'overview.md'
  - Installation: 'installation.md'
  - Modules: 
    - 'Read data': 'modules/read_data.md'
    - 'Spatial masking': 'modules/spatial_masking.md'
    - 'Spatial binning': 'modules/spatial_binning.md'
    - 'Prepare spectra': 'modules/prepare_spectra.md'
    - 'Stellar kinematics': 'modules/stellar_kinematics.md'
    - 'Emission lines': 'modules/emission_lines.md'
    - 'Stellar populations': 'modules/stellar_populations.md'
    - 'Line strengths': 'modules/line_strengths.md'



